/* Auto-generated by CMake from version.json – do not edit manually.
 * This file is regenerated every time CMake runs (idf.py build).
 * A pre-generated copy is committed so the build succeeds on first
 * checkout before CMake has been invoked. */
#pragma once
#define FW_VERSION_STR "1.0.0"
