/* Auto-generated by CMake from version.json – do not edit manually.
 * This file is regenerated every time CMake runs (idf.py build).
 * A pre-generated copy is committed so the build succeeds on first
 * checkout before CMake has been invoked.
 *
 * #ifndef guard: if FW_VERSION_STR is already defined on the compiler
 * command line (via add_compile_definitions in CMakeLists.txt), that
 * value takes precedence and this #define is skipped entirely.  Both
 * mechanisms set the same string, so the result is always correct. */
#pragma once
#ifndef FW_VERSION_STR
#define FW_VERSION_STR "1.0.0"
#endif
