"""
make_hotpatch.py — generate the Nextube Web UI update ZIP for a CI build.

data/web/index.html (shipped as index.html.gz) and data/web/version.txt
always ship unconditionally, every build — see the ALWAYS_INCLUDE comment
below for why. Everything else under data/web/ ships only if it actually
changed since WEBUI_DIFF_BASE (a git ref — the previous release tag for a
tag build, or the before-SHA for a branch/PR push — set by the workflow
from the same value it already computes for update-type classification).
No usable base (first-ever release, or the diff fails for any reason)
falls back to the full tree, so this can never silently ship an incomplete
update.

This used to unconditionally package the complete data/web/ tree every
build specifically so an update stayed safe to apply from any firmware
version, including skipped releases — that's no longer this file's job.
The device's own live-source stock-file repair (STOCK_FILES / SHA-256 /
stock_repair_task() in web_server.c, "Verify & Repair Stock Files" in the
web UI) now covers that case directly: any file this delta happens to miss
because a device skipped the release where it last changed can be re-fetched
individually, on demand, straight from the tag-pinned source. That's what
makes shipping only a delta here safe rather than reintroducing the gap the
old always-include-everything behavior used to guard against.

Additionally includes any paths listed in hotpatch_extras.txt at the repo root
(unaffected by any of the above — that's a separate, already-curated list).

Environment variables (set by the workflow before calling this script):
  BUILD_VER      — version string used in the output filename, e.g. "1.2.0"
  WEBUI_DIFF_BASE — git ref to diff data/web/ against (optional; empty/unset
                    ships the full tree, same as this script's old behavior)
"""

import gzip
import os
import subprocess
import sys
import zipfile

# index.html is shipped gzip-compressed only.  serve_static() on the device
# serves "<path>.gz" verbatim with Content-Encoding: gzip (the browser inflates
# it), so the ~308 KB shell costs ~73 KB of flash and ~¼ the per-request CPU.
# The plain file is excluded from the zip so it never lands on LittleFS.
GZIP_ONLY = {'web/index.html'}

# Always ship, unconditionally, regardless of WEBUI_DIFF_BASE:
#
# web/index.html — it's the one stock file the on-device repair mechanism
# deliberately can't reach (see hp_drop_stale_index() / STOCK_FILES's
# exclusion comment in web_server.c — the plain file only exists
# pre-first-hotpatch, so neither "index.html" nor "index.html.gz" alone is
# ever a reliable presence signal to verify against). A hotpatch is
# therefore the ONLY delivery path for this file. Free in practice when it
# hasn't actually changed — hp_file_unchanged()'s CRC32 write-skip means
# shipping it every time costs no flash write on a device that already has
# this exact content.
#
# web/version.txt — regenerated fresh at BUILD TIME (root CMakeLists.txt,
# and again just before this script runs — see the workflow) and NEVER
# committed to git, so a git diff against any base can never see it as
# "changed" no matter what fs_version actually is this release — it would
# be silently dropped from every hotpatch under the same diff filter as
# everything else in data/web/, breaking the version-mismatch banner's
# ability to ever clear after a patch. Same "always include, trivially
# cheap when unchanged" reasoning as index.html.
ALWAYS_INCLUDE = {'web/index.html', 'web/version.txt'}

build_ver = os.environ.get('BUILD_VER')
if not build_ver:
    print('ERROR: BUILD_VER environment variable is not set', file=sys.stderr)
    sys.exit(1)

zip_path = f'artifacts/nextube-WebUI-v{build_ver}.zip'


def changed_files_since(base, subtree):
    """Repo-relative paths that differ between `base` and HEAD under
    `subtree`, or None if that can't be determined (no base given, git
    unavailable, or the ref doesn't exist in this checkout)."""
    if not base:
        return None
    try:
        out = subprocess.run(
            ['git', 'diff', '--name-only', base, 'HEAD', '--', subtree],
            capture_output=True, text=True, check=True,
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f'  [web] git diff against "{base}" failed ({e}) — falling back to full tree')
        return None
    return {line.strip() for line in out.splitlines() if line.strip()}


to_include = set()

for rel in ALWAYS_INCLUDE:
    if os.path.isfile(os.path.join('data', rel)):
        to_include.add(rel)
    else:
        print(f'  [warn] {rel} not found on disk — expected to always be generated by this point')

# Everything else under data/web/
web_all = set()
for root, _dirs, files in os.walk('data/web'):
    for fn in files:
        abs_path = os.path.join(root, fn)
        rel = os.path.relpath(abs_path, 'data').replace(os.sep, '/')
        web_all.add(rel)
web_all -= ALWAYS_INCLUDE

diff_base = os.environ.get('WEBUI_DIFF_BASE', '').strip()
changed = changed_files_since(diff_base, 'data/web') if diff_base else None

if changed is None:
    print('  [web] no usable diff base — including the full data/web/ tree')
    web_to_include = web_all
else:
    # git diff paths are repo-relative ("data/web/foo.js"); rewrite to match
    # web_all's data/-relative convention. A file git reports as changed but
    # that no longer exists on disk (deleted) needs no inclusion — this
    # mechanism has never deleted anything from a device, consistent with
    # how it's always worked.
    changed_rel = {os.path.relpath(p, 'data').replace(os.sep, '/')
                   for p in changed if p.startswith('data/web/')}
    web_to_include = web_all & changed_rel
    print(f'  [web] {len(web_to_include)}/{len(web_all)} file(s) changed since {diff_base}')

to_include |= web_to_include

# Extra assets declared in hotpatch_extras.txt — unaffected by the above,
# this is already a curated (not "everything") list.
# Add one path per line (relative to data/), e.g.:
#   images/themes/NixieOY/Numbers/5.jpg
#   audio/bell.mp3
# Lines starting with '#' and blank lines are ignored.
# config.json is always excluded even if listed.
# Clear this file after a full LittleFS flash release.
extras_file = 'hotpatch_extras.txt'
if os.path.isfile(extras_file):
    with open(extras_file) as f:
        for line in f:
            rel = line.strip()
            if not rel or rel.startswith('#'):
                continue
            if rel == 'config.json':
                print(f'  [skip] {rel} — config is never distributed')
                continue
            full = os.path.join('data', rel)
            if os.path.isfile(full):
                to_include.add(rel)
            else:
                print(f'  [warn] hotpatch_extras.txt: {rel} not found on disk, skipping')

to_include = sorted(to_include)

print(f'Web UI ZIP contents ({len(to_include)} files):')
for f in to_include:
    print(f'  {f}')

os.makedirs('artifacts', exist_ok=True)
with zipfile.ZipFile(zip_path, 'w', compression=zipfile.ZIP_STORED) as zf:
    for rel in to_include:
        src = os.path.join('data', rel)
        if rel in GZIP_ONLY:
            # Store the gzip bytes under "<rel>.gz".  The zip itself stays
            # STORE-method (the device unzip only handles stored entries); the
            # gzip payload is already-compressed bytes written verbatim.
            with open(src, 'rb') as fh:
                raw = fh.read()
            blob = gzip.compress(raw, 9)
            zf.writestr(rel + '.gz', blob)
            print(f'  gzip   {rel} -> {rel}.gz  ({len(raw):,} -> {len(blob):,} B)')
        else:
            zf.write(src, rel)

sz = os.path.getsize(zip_path)
print(f'Web UI ZIP written: {zip_path} ({sz:,} bytes)')
